# Generated by Django 3.0.7 on 2020-07-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disctrict',
            name='Active',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disctrict',
            name='Confirmed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disctrict',
            name='Death',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disctrict',
            name='Recovered',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
