# Generated by Django 3.0.7 on 2020-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200703_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disctrict',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
