# Generated by Django 3.0.7 on 2020-07-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200703_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disctrict',
            new_name='District',
        ),
    ]
