# Generated by Django 3.0.7 on 2020-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20200703_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateReport',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('confirmed', models.IntegerField()),
                ('Active', models.IntegerField()),
                ('Death', models.IntegerField()),
                ('Recovered', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
