# Generated by Django 3.0.7 on 2020-07-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20200717_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateReport',
        ),
    ]
