# Generated by Django 3.0.7 on 2020-07-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_delete_datereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateReport',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
                ('confirmed', models.IntegerField()),
                ('Active', models.IntegerField()),
                ('Death', models.IntegerField()),
                ('Recovered', models.IntegerField()),
            ],
        ),
    ]
