# Generated by Django 3.0.7 on 2020-07-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_datereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datereport',
            old_name='id',
            new_name='date',
        ),
    ]
