# Generated by Django 3.0.7 on 2020-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20200717_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('total_sent', models.IntegerField()),
                ('sent', models.IntegerField()),
                ('total_positive', models.IntegerField()),
                ('new_positive', models.IntegerField()),
            ],
        ),
    ]
